# Generated by Django 4.2.1 on 2023-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabelPetugas',
            fields=[
                ('nidn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=50)),
                ('tipe', models.CharField(max_length=1)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
