# Generated by Django 4.2.1 on 2023-05-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabelMhs',
            fields=[
                ('nim', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('prodi', models.CharField(max_length=30)),
                ('Fakultas', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
