# Generated by Django 4.2.1 on 2023-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabelmhs',
            old_name='Fakultas',
            new_name='fakultas',
        ),
        migrations.AlterField(
            model_name='tabelmhs',
            name='nim',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
