# Generated by Django 4.2.1 on 2023-05-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_alter_tabelmhs_password'),
        ('yudisium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelyudisium',
            name='nim',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.tabelmhs'),
            preserve_default=False,
        ),
    ]
