# Generated by Django 4.2.1 on 2023-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yudisium', '0004_alter_tabelyudisium_nim'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelyudisium',
            name='tanggal',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
