# Generated by Django 4.2.1 on 2023-05-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabelSidang',
            fields=[
                ('id_sidang', models.AutoField(primary_key=True, serialize=False)),
                ('s_persetujuan', models.FileField(upload_to='surat_persetujuan/')),
                ('s_permohonan', models.FileField(upload_to='surat_permohonan/')),
                ('s_undangan', models.FileField(upload_to='surat_undangan/')),
                ('bukti_pembayaran', models.FileField(upload_to='bukti_pembayaran/')),
                ('krs', models.FileField(upload_to='krs/')),
                ('kartu_bimbingan', models.FileField(upload_to='kartu_bimbingan/')),
                ('transkrip', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
