# Generated by Django 4.2.1 on 2023-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelsidang',
            name='transkrip',
            field=models.FileField(upload_to='transkrip/'),
        ),
    ]
