# Generated by Django 4.2.1 on 2023-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidang', '0002_alter_tabelsidang_transkrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelsidang',
            name='bukti_pembayaran',
            field=models.FileField(upload_to='sidang/bukti_pembayaran/'),
        ),
        migrations.AlterField(
            model_name='tabelsidang',
            name='kartu_bimbingan',
            field=models.FileField(upload_to='sidang/kartu_bimbingan/'),
        ),
        migrations.AlterField(
            model_name='tabelsidang',
            name='krs',
            field=models.FileField(upload_to='sidang/krs/'),
        ),
        migrations.AlterField(
            model_name='tabelsidang',
            name='s_permohonan',
            field=models.FileField(upload_to='sidang/surat_permohonan/'),
        ),
        migrations.AlterField(
            model_name='tabelsidang',
            name='s_persetujuan',
            field=models.FileField(upload_to='sidang/surat_persetujuan/'),
        ),
        migrations.AlterField(
            model_name='tabelsidang',
            name='s_undangan',
            field=models.FileField(upload_to='sidang/surat_undangan/'),
        ),
        migrations.AlterField(
            model_name='tabelsidang',
            name='transkrip',
            field=models.FileField(upload_to='sidang/transkrip/'),
        ),
    ]
