# Generated by Django 4.2.1 on 2023-06-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_alter_tabelmhs_password'),
        ('sidang', '0005_alter_tabelsidang_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelsidang',
            name='nim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.tabelmhs'),
        ),
    ]
