# Generated by Django 4.2.1 on 2023-06-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidang', '0007_tabelwaktusidang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelwaktusidang',
            name='waktu_sidang',
            field=models.DateTimeField(),
        ),
    ]
