# Generated by Django 4.2.1 on 2023-06-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_alter_tabelmhs_password'),
        ('sidang', '0008_alter_tabelwaktusidang_waktu_sidang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelwaktusidang',
            name='nim',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.tabelmhs'),
            preserve_default=False,
        ),
    ]
