# Generated by Django 4.2.1 on 2023-06-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidang', '0009_remove_tabelwaktusidang_id_sidang_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tabelWaktuSidang',
        ),
    ]
